[package]
name = "rmk"

version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
snafu.workspace = true
anyhow.workspace = true

console-subscriber.workspace = true
tracing.workspace = true

tokio.workspace = true
tokio-util.workspace = true

opendal.workspace = true
opendal-mount.workspace = true

config.workspace = true
directories.workspace = true
tempfile.workspace = true

serde.workspace = true
toml.workspace = true
serde_json.workspace = true

bytes.workspace = true

lazy_static.workspace = true

derive_builder.workspace = true

indextree.workspace = true

futures.workspace = true

rmk_format = { path = "../rmk_format" }
